export const CONTACT_LIST_GET_SUCCESS = 'CONTACT_LIST_GET_SUCCESS';

export const CONTACT_GET_CONTACT_SUCCESS = 'CONTACT_GET_CONTACT_SUCCESS';
export const CONTACT_RESET_CONTACT = 'CONTACT_RESET_CONTACT';

export const NOTIFICATIONS_SHOW_ERROR = 'NOTIFICATIONS_SHOW_ERROR';
export const NOTIFICATIONS_SHOW_INFO = 'NOTIFICATIONS_SHOW_INFO';
export const NOTIFICATIONS_CLEAR_MESSAGES = 'NOTIFICATIONS_CLEAR_MESSAGES';
