export const CONTACT_LIST_GET_SUCCESS = 'CONTACT_LIST_GET_SUCCESS';

export const CONTACT_GET_CONTACT_SUCCESS = 'CONTACT_GET_CONTACT_SUCCESS';
export const CONTACT_RESET_CONTACT = 'CONTACT_RESET_CONTACT';

export const NOTIFICATION_SHOW_ERROR = 'NOTIFICATION_SHOW_ERROR';
export const NOTIFICATION_SHOW_INFO = 'NOTIFICATION_SHOW_INFO';
export const NOTIFICATION_CLEAR_MESSAGES = 'NOTIFICATION_CLEAR_MESSAGES';
